import type { Metadata } from "next";
import "./globals.css";
import { CartContextProvider } from "./CartContextProvider";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { AuthContextProvider } from "./AuthContextProvider";

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      //   className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 flex flex-col min-h-screen`}
      >
        <AuthContextProvider>
          <CartContextProvider>
            <header>
              <Navbar />
            </header>
            <main className="flex-grow">{children}</main>
          </CartContextProvider>
        </AuthContextProvider>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
