import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "./CartContextProvider";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <CartContextProvider>
          <header>
            <Navbar />
          </header>

          {children}
        </CartContextProvider>
        <footer>
          {/* footer part will be improved */}
          <div className="text-center text-gray-500 text-sm mt-4">
            © {new Date().getFullYear()} E-Commerce. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
